stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - src/entity/config_entity.py
      - src/pipeline/train_pipeline_stage.py
    outs:
      - artifact/data_ingestion/feature_store/data.csv
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv

  data_validation:
    cmd: python src/components/data_validation.py
    deps:
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv
      - src/components/data_validation.py
      - src/entity/config_entity.py
      - src/pipeline/train_pipeline_stage.py
    outs:
      - artifact/data_validation/validation_report.yaml

  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv
      - artifact/data_validation/validation_report.yaml
      - src/components/data_transformation.py
      - src/pipeline/train_pipeline_stage.py
    outs:
      - artifact/data_transformation/transformed/train.npy
      - artifact/data_transformation/transformed/test.npy
      - artifact/data_transformation/transformed_object/preprocessing.pkl

  model_trainer:
    cmd: python src/components/model_trainer.py
    deps:
      - artifact/data_transformation/transformed/train.npy
      - artifact/data_transformation/transformed/test.npy
      - artifact/data_transformation/transformed_object/preprocessing.pkl
      - src/components/model_trainer.py
      - src/pipeline/train_pipeline_stage.py
    outs:
      - artifact/model_trainer/trained_model/model.pkl
      - artifact/model_trainer/model_report.yaml
