# random_forest:
#   n_estimators: 200
#   criterion: 'entropy'
#   max_depth: 10
#   min_samples_split: 7
#   min_samples_leaf: 6
#   max_features: "sqrt"
#   bootstrap: true
#   random_state: 42
gradient_boosting:
  learning_rate: 0.2
  max_depth: 5
  min_samples_leaf: 2
  min_samples_split: 10
  n_estimators: 200
  subsample: 1.0
  random_state: 42
